# Generated by Django 5.2.4 on 2025-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='user',
        ),
        migrations.AddField(
            model_name='reward',
            name='participant_name',
            field=models.CharField(default='Unknown Participant', max_length=100),
        ),
        migrations.AlterField(
            model_name='reward',
            name='badge',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('star', 'Star')], max_length=20, null=True),
        ),
    ]
