# Generated by Django 5.2.4 on 2025-09-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='waste_reports/')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
